### ISSUE TITLE
The import java.io.LineStream cannot be resolved!

### ISSUE THREAD

**Issue by vinayakap** [confabulation/symbolic#1]
Related to above error in import section, i got three more errors stating 
1. Multiple markers at this line
    - TODO
    - The method shell(String, Class<?>, LineStream, PrintStream, PrintStream) from the type Main refers to the missing type LineStream
1. The method shell(String, Class<?>, LineStream, PrintStream, PrintStream) from the type Main refers to the missing type LineStream
2. LineStream cannot be resolved to a type.

Plz let me know what is my mistake.

Screenshots:
![1](https://cloud.githubusercontent.com/assets/7909766/14433931/f5b580be-002d-11e6-8e11-02b4ec5c64ef.png)
![2](https://cloud.githubusercontent.com/assets/7909766/14433932/f5ee5524-002d-11e6-87df-dcc41e2177e2.png)
![3](https://cloud.githubusercontent.com/assets/7909766/14433933/f62680fc-002d-11e6-8965-9180fe8ecbbb.png)
![0](https://cloud.githubusercontent.com/assets/7909766/14433935/f662596a-002d-11e6-86b1-a3d9c07e390b.png).!

**Comment by bernardpaulus** [comment]
Hello Vinayak,

Sorry for the brief *ahem :) * deIay: it seems I never noticed this issue.

That said, I'm looking into it: I started working to make this project buildable in a standard way via maven. This will probably also solve your problem.

I'll update you when I'm done.

Cheers and thank you for the feedback!
